resources:
  containers:
  - container: octodns
    image: im5tu/octodns:latest

container: octodns

variables:
- group: DNS

steps:
- script: 'octodns-sync --config-file=config/production.yml'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Test DNS Changes'
  env:
    CLOUDFLARE_EMAIL: $(CLOUDFLARE_EMAIL)
    CLOUDFLARE_TOKEN: $(CLOUDFLARE_TOKEN)
    DNSIMPLE_ACCOUNT: $(DNSIMPLE_ACCOUNT)
    DNSIMPLE_TOKEN: $(DNSIMPLE_TOKEN)

- script: 'octodns-sync --config-file=config/production.yml'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Apply DNS Changes'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  env:
    CLOUDFLARE_EMAIL: $(CLOUDFLARE_EMAIL)
    CLOUDFLARE_TOKEN: $(CLOUDFLARE_TOKEN)
    DNSIMPLE_ACCOUNT: $(DNSIMPLE_ACCOUNT)
    DNSIMPLE_TOKEN: $(DNSIMPLE_TOKEN)