resources:
  containers:
  - container: octodns
    image: im5tu/octodns:latest

container: octodns

variables:
- group: DNS

steps:
- script: 'octodns-sync --config-file=config\production.yml'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Test DNS Changes'