resources:
  containers:
  - container: octodns
    image: blob/octodns

#pool:
  #vmImage: 'ubuntu-16.04'

container: octodns

variables:
- group: DNS

steps:
- script: 'octodns-sync --config-file=config\production.yml'
  displayName: 'Test DNS Changes'