---
? ''
: - ttl: 3600
    type: A
    value: 151.101.41.147
  - ttl: 3600
    type: AAAA
    value: 2a04:4e42:a::403
  - ttl: 3600
    type: MX
    values:
    - exchange: mx1.emailsrvr.com.
      preference: 10
    - exchange: mx2.emailsrvr.com.
      preference: 20
  - ttl: 3600
    type: TXT
    values:
    - ALIAS for dnbmth.github.io
    - v=spf1 include:emailsrvr.com ~all
autodiscover:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: CNAME
  value: autodiscover.emailsrvr.com.
meet:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: A
  value: 188.166.203.69
videos:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: A
  value: 188.166.203.69
www:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: CNAME
  value: dnbmth.io.
