---
? ''
: - octodns:
      cloudflare:
        proxied: true
    ttl: 3600
    type: A
    value: 185.199.108.153
  - ttl: 3600
    type: MX
    values:
    - exchange: mx1.emailsrvr.com.
      preference: 10
    - exchange: mx2.emailsrvr.com.
      preference: 20
  - ttl: 3600
    type: TXT
    value: v=spf1 include:emailsrvr.com ~all
_github-challenge-signaloneltd:
  ttl: 3600
  type: TXT
  value: d7e041b559
autodiscover:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: CNAME
  value: autodiscover.emailsrvr.com.
www:
  octodns:
    cloudflare:
      proxied: true
  ttl: 3600
  type: CNAME
  value: signalone.cloud.
